version: "2.2"
services:
  tp-link-api-bridge:
    build: .
    container_name: tp-link-api-bridge
    volumes:
      - ./config.json:/home/node/tp-link-modem-router-master/config.json
    ports: 
      - 3000:3000
    restart: unless-stopped
    init: true